### ISSUE TITLE
Add meta data

### ISSUE THREAD

**Issue by simonhaenisch** [equippers/equippers.de#2]
- [ ] [Facebook Open Graph](http://ogp.me)
- [ ] [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards)
- [ ] [Google Structured Data](https://developers.google.com/search/docs/guides/intro-structured-data)
